const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{Fundo: 0},
	{Sólido: 0},
	{Chão: 0},
	{Fixar: 0},
	{Luiti: 0},
	{Arvore: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{Jogador: 0},
	{Teclado: 0},
	{Senóide: 0},
	{luzPontuação: 0},
	{Âncora: 0},
	{pontuação: 0},
	{luzPontuaçãoPontos: 0},
	{ação: 0},
	{InimigoSombra: 0},
	{cogumeloPodre: 0},
	{marcador: 0},
	{ChãoVert: 0},
	{ChãoHor: 0},
	{Vitória: 0},
	{Áudio: 0},
	{abismo: 0},
	{GameOver: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{play: 0},
	{Iniciar: 0},
	{Mouse: 0},
	{Reiniciar: 0},
	{Início: 0},
	{Sprite4: 0},
	{pontos: 0}
];

self.InstanceType = {
	Fundo: class extends self.ITiledBackgroundInstance {},
	Chão: class extends self.ITiledBackgroundInstance {},
	Luiti: class extends self.ISpriteInstance {},
	Arvore: class extends self.ISpriteInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	luzPontuação: class extends self.ISpriteInstance {},
	pontuação: class extends self.ITextInstance {},
	luzPontuaçãoPontos: class extends self.ISpriteInstance {},
	InimigoSombra: class extends self.ISpriteInstance {},
	cogumeloPodre: class extends self.ISpriteInstance {},
	marcador: class extends self.ISpriteInstance {},
	ChãoVert: class extends self.ITiledBackgroundInstance {},
	ChãoHor: class extends self.ITiledBackgroundInstance {},
	Vitória: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	abismo: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	Iniciar: class extends self.IButtonInstance {},
	Mouse: class extends self.IInstance {},
	Reiniciar: class extends self.IButtonInstance {},
	Início: class extends self.IButtonInstance {},
	Sprite4: class extends self.ISpriteInstance {}
}